version: "3.9"

services:
  db:
    image: mysql:8.4
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}      
      MYSQL_USER: ${DB_USER}           
      MYSQL_PASSWORD: ${DB_PASSWORD}

    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - backend_frontend_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    image: ${DOCKERHUB_USERNAME}/lemp-backend:latest
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
    networks:
      - backend_frontend_net
    depends_on:
      db:
        condition: service_healthy
      mqtt:
        condition: service_started

  mqtt:
    image: eclipse-mosquitto:2
    volumes:
      - ./mqtt-chat/mosquitto/config:/mosquitto/config/mosquitto.conf:ro
      - ./mqtt-chat/mosquitto/data:/mosquitto/data
      - ./mqtt-chat/mosquitto/log:/mosquitto/log
    ports:
      - "1884:1883"
      - "9002:9001"
    networks:
      - backend_frontend_net
    restart: unless-stopped

  mqtt-logger:
    image: ${DOCKERHUB_USERNAME}/mqtt-logger:latest
    env_file: .env
    depends_on:
      - mqtt
      - db
    networks:
      - backend_frontend_net
    restart: unless-stopped

  mqtt-api:
    image: ${DOCKERHUB_USERNAME}/mqtt-api:latest
    env_file: .env
    depends_on:
      - db
    ports:
      - "5002:5000"
    networks:
      - backend_frontend_net

  frontend:
    image: ${DOCKERHUB_USERNAME}/lemp-frontend:latest
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - backend_frontend_net
    ports:
      - "8001:80"

volumes:
  db_data:
  mosquitto_data:
  mosquitto_log:

networks:
  backend_frontend_net: