version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883" # MQTT TCP
      - "9001:9001" # WebSocket
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  logger:
    build: ./logger
    env_file: ./logger/.env
    depends_on:
      - mosquitto

  web:
    image: nginx
    volumes:
      - ./web/html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - mosquitto
